### ISSUE TITLE
Trigger events

### ISSUE THREAD

**Issue by kingsloi** [shershen08/vue-masonry#5]
Hi,

I'm using Vuex to show data on my dashboard page. I load a few things after page load, so I'm looking to trigger one of the events to redraw the masonary grid. 

I'm not able to access the `Events` eventhub, so I'm unsure how to trigger. Any ideas?

**Comment by shershen08** [comment]
Hi, I'll check that and think of the options by tonight

**Comment by kingsloi** [comment]
@shershen08, you're a good man

**Comment by shershen08** [comment]
Can you check if you maybe have similar misuse of the plugin (https://github.com/shershen08/vue-masonry/issues/1) ?
Since the elements added to the DOM the internal plugin's events will be triggered automatically and masonry.layout will be called.

**Comment by kingsloi** [comment]
I don't use a for loop to call my "blocks" I have them manually typed out into my component such as:

```html
<div v-masonry transition-duration="0.3s" item-selector=".item">
    <div v-masonry-tile class="item">
       <h3>Title 1</h3>
       <div>3000</div>
    </div>
    <div v-masonry-tile class="item">
       <h3>Title 2</h3>
       <div>3000</div>
    </div>
    <div v-masonry-tile class="item">
       <h3>Title 3</h3>
       <div>3000</div>
    </div>
</div>
```

Which I take is incorrect as it doesn't trigger the events, so I have to use a for-loop?

**Comment by shershen08** [comment]
I got your point, yes I see the problem, working on it

**Comment by kingsloi** [comment]
@shershen08 dank je wel

**Comment by shershen08** [comment]
@kingsloi I've experimented with the static setup you had. And event in that case the the masonry layout worked out correctly. 
I suppose it's because this line of code in the plugin 

`var masonry = new Masonry(el, collectOptions(el.attributes))`

[here](https://github.com/shershen08/vue-masonry/blob/master/src/masonry.plugin.js#L38) leads to the same [vanilla js initialization scenario](http://masonry.desandro.com/#initialize-with-vanilla-javascript) as describe on masonry website here.

I am now creating a reproducible demo on jsfiddle and will share the link shortly.

**Comment by shershen08** [comment]
Any news on your issue @kingsloi ?

**Comment by kingsloi** [comment]
@shershen08, sorry I haven't had a chance just yet - I'll take a look and let you know later

**Comment by kingsloi** [comment]
@shershen08, ok, I think it was a weird edge case with two packages using the same class on something else - I just copied your example and it worked perfect. Thanks for helping!
