### ISSUE TITLE
Multiple instances issue

### ISSUE THREAD

**Issue by matt-shine** [shershen08/vue-masonry#59]
I have two (vuetify) tabs, each of which has a masonry element. If I add an item to the active tab and then switch tabs, all elements of the newly selected tab are stacked on top of each other.

I'm calling redrawVueMasonry ~~on the add~~, when a tab switch happens, but it doesn't seem to fix the problem... Any ideas?

edit: I appreciate your work on this package btw!

**Comment by shershen08** [comment]
@matt-shine I'll try to reproduce the case and get back to you asap

**Comment by shershen08** [comment]
@matt-shine I could reproduce your problem.
this happens when the masonry content in the not-visible tab then becoming shown again the masonry bindings seem inactive. however the content absolute positioning inlined CSS that masonry plugin adds - is still there, which looks like a good sing to me.
I'll try to investigate a bit more what could be the solution and get back to you

**Comment by r-f-j-thomas** [comment]
This is causing me problems too. @matt-shine did you find a workaround?

**Comment by z2013** [comment]
Having this issue as well with multiple instances... any workarounds?

**Comment by asgarth** [comment]
Same problem here. Any news on this or workarounds available?

**Comment by asgarth** [comment]
@shershen08 not sure if this can help you, but from what I've seen the problem is that the second instance to be loaded override the events listener defined by the first instance. So the first instance stop working as expected.

From my point of view a good workaround (before finding a final solution) could be to just add a method to reinitialize the listeners.

**Comment by ryanhovland** [comment]
I'm running into this issue as well. I have a section of my site that has a masonry grid on it. Within that section, I have child routes that also have masonry grids. When navigating away from a child page with a masonry grid, the parent masonry grid breaks. 

It probably depends on your setup, but using `<keep-alive></keep-alive>` around my router-view was a fix for me.

**Comment by ryanhovland** [comment]
@shershen08 I guess I'm not really sure exactly what's happening under the hood. It seems like when an instance of the masonry grid is removed from the DOM, it tries to destroy it. But instead of destroying the instance that left, it destroys all instances in the DOM. Just seems like a scope issue.

Once it breaks, the HTML markup of the masonry grid still seems to be intact, but all of its inline styles are cleared. So there's no longer top/left positioning, etc. No errors ever appear in the console.

Btw, thanks for your work on this component!

**Comment by asgarth** [comment]
I had the issue because my component is inside a `<keep-alive></keep-alive>` block.

So when I switch view the old instance is not destroyed and when the original component is activated again the instance stop receiving events.

**Comment by asgarth** [comment]
@shershen08 exactly. Without the keep-alive the component is destroyed and created from scratch so everything works.

**Comment by shershen08** [comment]
what I came to is that 
in mu test scenario I have 2 routes with same masonry items added on scroll
1) items from one route are appended to another
2) inline style tags of items are cleared after route switch - 
<img width="495" alt="screen shot 2018-12-16 at 22 50 11" src="https://user-images.githubusercontent.com/1363772/50059281-2c7a4700-0185-11e9-8434-1c042233f21c.png">

**Comment by asgarth** [comment]
From me also all the events stop working. I cannot force a relayout or call redrawVueMasonry.

**Comment by headione** [comment]
First of all: Thanks for this awesome plugin! ❤️

I'm not sure if it helps but I also had this issue with the router-view wrapped in `<keep-alive>` and I think I fixed it by redrawing masonry within the `activated ()` state and it looks like it solved the problem for me.

```
activated () {
    this.$redrawVueMasonry()
},
```

**Comment by benjamindedonder** [comment]
Yes, this is a very cool feature you are bringing to Vue.js. Your work is very much appreciated.

Is there any progress on this? I am having the same issue.

**Comment by shershen08** [comment]
@benjamindedonder did you check the items in this thread:
1) avoid <keep-alive>
2) try using this.$redrawVueMasonry() ?

**Comment by benjamindedonder** [comment]
Yes, I have. In my case I am displaying a list of images with vue-masonry and allowing the user to select these images from elsewhere via a dialog in which I again use vue-masonry. After the dialog closes I am not able to request a redraw for the first mentioned list of images.
