### ISSUE TITLE
Blocks are overlapping

### ISSUE THREAD

**Issue by azhard4int** [shershen08/vue-masonry#9]
Hi,

@shershen08 great work done by you mate, we are experiencing a problem when the posts have the lazy load images enabled and their height is dynamically adjusted. Here is a link to the screenshot [http://prntscr.com/etgok7](http://prntscr.com/etgok7)

Div/Blocks are overlapping each other and we assigned the min-height to the box/div as well but in that case the distance/gap between items increases too much.

What do you suggest? If we use the callback for the lazy load images is it not going to slow down the application?

**Comment by shershen08** [comment]
Hi @azhard4int

**Comment by shershen08** [comment]
I see the problem on the screeshot. However that could be easier to debug if there was a code example of the problem using jsfiddle for example. 

Current version has an image loaded enabled so blocks should adjust correctly when images are loaded. 

Using callback is intended for cases when the dimensions of the content of your blocks changed somehow since last adjustment. It calls methods from original plugin so it's not adding too much overhead as I see it now.

**Comment by azhard4int** [comment]
@shershen08 The issue that was coming is due to vue-lazy-load images plugin.

As imagesLoaded is called instantly as soon as the new posts have been fetched instead when the image file has been downloaded. Right now, I have removed the v-lazy and it is working fine now.

I will further dig deep for the v-lazy-load and try to update here if we can resolve it using v-lazy-load.

**Comment by shershen08** [comment]
Thanks for the fast update @azhard4int. Closing this for now since it's not a vue-masonry issue directly. 
But you still welcome to update this topic here below. 

When I will be planning to add an Faq section with common cases and problems ppl come across I will reference this item there.

**Comment by cute-angelia** [comment]
masonry and lazyload , they are good friends , the essence is to get the true height and width of the picture
